[[main]]
  name    = "文章"
  pageRef = "posts"
  weight  = 10
  pre = "article"

[[main]]
  name    = "分类"
  pageRef = "categories"
  weight  = 20
  pre = "category"

[[main]]
  name    = "标签"
  pageRef = "tags"
  weight  = 30
  pre = "tag"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/zhuniao123" # 请替换为您的 GitHub 地址
  weight = 100

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:zhuniao123@gmail.com" # 请替换为您的邮箱地址
  weight = 110

[[main]]
  identifier = "rss"
  pre = "rss"
  url = "/index.xml"
  weight = 120
