colorScheme = "weaxsey"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed-fill"

[footer]
  showMenu = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "images/hero.jpg"
  layoutBackgroundBlur = true
  showRecent = true
  showRecentItems = 6
  cardView = true
  cardViewScreenWidth = true
  showMoreLink = true
  showMoreLinkDest = "/posts/"

[article]
  showDate = true
  showReadingTime = true
  showTableOfContents = true
  showHero = false
  showBreadcrumbs = false
  showPagination = true

[list]
  showBreadcrumbs = false
  showSummary = true
  cardView = true
  groupByYear = true
